### ISSUE TITLE
Basic documentation

### ISSUE THREAD

**Issue by h3xstream** [google/certificate-transparency-java#16]
I don't know if it is intended to be reused outside of Google.
If so, it would be nice to have the following basic documentation artifacts:
 - [x] README 
 - [x] Maven artifact snippet
 - [ ] Quick start code example

Thanks

**Comment by pphaneuf** [comment]
Just to clarify the status of this code: not only is this code intended to be used outside of Google, it was written specifically with this intent! I'm not certain we even use it internally, and it is used inside some CA software, AFAIK.

**Comment by mhutchinson** [comment]
Closing this issue. This repo is no longer being maintained. See the README for info.
