### ISSUE TITLE
Create a simple boolean example based on a certificate

### ISSUE THREAD

**Issue by ralfhauser** [google/certificate-transparency-java#26]
Is there anywhere a java code example that allows to hand over a X509Certificate and get a boolean answer whether it is good or not.

I would assume in my lay-person's understanding that the example would:
1) search the cert in the logs
a) validate its log entry (and provide the info when it was added to which log and that the log's Merkle proofs were good)
b) if invalid, add an explanation why it is not good (which logs it was found, but what was wrong with it)
2) if not found validate the SCTs
...

is there anything like this ?

**Comment by rivercartwright** [comment]
I am working on some example code.

**Comment by rivercartwright** [comment]
Just waiting on someone to review my pull request and merge it.

**Comment by mhutchinson** [comment]
Closing this issue. This repo is no longer being maintained. See the README for info.
