### ISSUE TITLE
Iterating over precert_entries from getLogEntries causes Serialization Exception

### ISSUE THREAD

**Issue by nbka** [google/certificate-transparency-java#34]
Example:
```
HttpLogClient ctClient = new HttpLogClient("https://ct.googleapis.com/logs/argon2019/ct/v1/");
List<ParsedLogEntry> entries = ctClient
              .getLogEntries(0,3);
```
Iterating over entries will raise exception "org.certificatetransparency.ctlog.serialization.SerializationException: Extra data corrupted" since entries at index positions 0 and 1 are precerts.

**Comment by mhutchinson** [comment]
Closing this issue. This repo is no longer being maintained. See the README for info.
