### ISSUE TITLE
Code quality: Address Javadoc warnings

### ISSUE THREAD

**Issue by codingllama** [google/certificate-transparency-java#7]
Context: #6

**Comment by alexanderkjall** [comment]
I investigated this, and 90% of the warnings comes from the class CT that is generated by protobuf.

There is an open ticket in protobuf about not generating so many errors here: https://github.com/google/protobuf/issues/304

I fixed the other two javadoc errors here: https://github.com/alexanderkjall/certificate-transparency-java/tree/fix-javadoc

But maybe we should suppress all javadoc errors until the protobuf people fix their stuff?

**Comment by pphaneuf** [comment]
Or, alternatively, finish off #1, and just drop the dependency entirely? :wink:

**Comment by codingllama** [comment]
Huh. I wasn't expecting it to be a protobuf/Javadoc issue. I would prefer either ignoring warnings from generated sources (not sure how) or doing nothing at all. At least legit warnings won't go silent that way.

Ofc, #1 makes it a moot point, as Pierre said. I've been meaning to have a go at it, but that's not my main focus right now, so it may take a while.

**Comment by alexanderkjall** [comment]
I tried to search for solutions to suppressing warnings for just that class, without success.

**Comment by mhutchinson** [comment]
Closing this issue. This repo is no longer being maintained. See the README for info.
