### ISSUE TITLE
Publish ct-java to OSSRH

### ISSUE THREAD

**Issue by codingllama** [google/certificate-transparency-java#9]
Guide: http://central.sonatype.org/pages/ossrh-guide.html
Requirements: http://central.sonatype.org/pages/requirements.html

PR #6 addresses the requirements, so what's left is signing up for account and publishing it.

@AlCutter, I'd like to know your thoughts on this before proceeding.

**Comment by lvh** [comment]
Is there anything non-Googlers can do to contribute to this?

**Comment by codingllama** [comment]
Hey Laurens,

AFAICT, we're in good shape in terms of requirements. I'd like to sync with @AlCutter before moving forward, but at this point all that's left is doing the registrations and drafting a "release procedure" for the team, however it may look like. I do think that those steps should fall on the project maintainers.

It's good to know that there's interest, though. I'll not be so bold as to make any promises, but I'll see if I can get the ball rolling. :)

**Comment by codingllama** [comment]
I've just filed our new project ticket: https://issues.sonatype.org/browse/OSSRH-32521 (not sure if people can see this).

I'll update here once it moves forward.

**Comment by codingllama** [comment]
We've got a project. :)

I've just pushed [0.1.0-SNAPSHOT](https://oss.sonatype.org/content/repositories/snapshots/org/certificate-transparency/ctlog/0.1.0-SNAPSHOT/) to OSSRH. Here's a simple pom that uses it:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>example</groupId>
  <artifactId>example</artifactId>
  <version>1.0-SNAPSHOT</version>

  <repositories>
    <repository>
      <id>ossrh-snapshots</id>
      <url>https://oss.sonatype.org/content/repositories/snapshots</url>
    </repository>
  </repositories>

  <dependencies>
    <dependency>
      <groupId>org.certificate-transparency</groupId>
      <artifactId>ctlog</artifactId>
      <version>0.1.0-SNAPSHOT</version>
    </dependency>
  </dependencies>

</project>
```

I'll see about releasing 0.1.0 now.

**Comment by codingllama** [comment]
Pushed 0.1.0: https://repo.maven.apache.org/maven2/org/certificate-transparency/ctlog/0.1.0/.
